spring:
  datasource:
    url: ${DB_URL:jdbc:h2:file:./data/siege-db}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}
      path: /h2-console

external:
  swarfarm:
    base-url: ${SWARFARM_BASE_URL:https://swarfarm.com/api/v2}
    image-base-url: ${SWARFARM_IMAGE_BASE_URL:https://swarfarm.com/static/herders/images/monsters}

logging:
  level:
    #    org.hibernate.SQL: debug
    org.springframework.security: DEBUG
