spring:
  datasource:
    url: ${DB_URL}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}

  h2:
    console:
      enabled: false
