spring:
  datasource:
    url: ${DB_URL}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:5}
      minimum-idle: ${DB_MIN_IDLE:1}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      validation-timeout: ${DB_VALIDATION_TIMEOUT:5000}
      idle-timeout: ${DB_IDLE_TIMEOUT:60000}
      max-lifetime: ${DB_MAX_LIFETIME:300000}
      keepalive-time: ${DB_KEEPALIVE_TIME:120000}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}

  h2:
    console:
      enabled: false
